### ISSUE TITLE
Latest commit pushed merge conflict markers

### ISSUE THREAD

**Issue by trevorriles** [PyMNtos/stacks#19]
The most recent commit, 43f68bb871b210a87962690dc374590e20156d67, includes the merge conflict markers. We should probably revert this (to preserve history) by running:

`git revert 43f68bb871b210a87962690dc374590e20156d67`

I can't do it right now, but can get around to it later if it hasn't been taken care of.

We need to keep the main repo as clean as possible and should use pull requests to avoid these mistakes.

**Comment by maestrofjp** [comment]
Ah, my bad on the markers. I should double checked better.  This is what I get for using a new merge tool...
